title: Grace Esthetics YEG
author: ammyamazing
email: ammyamazing+gracestheticsyeg@gmail.com
description: >-
   ğ˜ˆğ˜¥ğ˜·ğ˜¢ğ˜¯ğ˜¤ğ˜¦ğ˜¥ ğ˜§ğ˜¢ğ˜¤ğ˜ªğ˜¢ğ˜­ğ˜´
   ğ˜‹ğ˜¦ğ˜³ğ˜®ğ˜¢ğ˜±ğ˜­ğ˜¢ğ˜¯ğ˜ªğ˜¯ğ˜¨
   ğ˜”ğ˜ªğ˜¤ğ˜³ğ˜°ğ˜¥ğ˜¦ğ˜³ğ˜®ğ˜¢ğ˜£ğ˜³ğ˜¢ğ˜´ğ˜ªğ˜°ğ˜¯
   ğ˜‰ğ˜³ğ˜°ğ˜¸ & ğ˜“ğ˜¢ğ˜´ğ˜© ğ˜šğ˜¦ğ˜³ğ˜·ğ˜ªğ˜¤ğ˜¦ğ˜´
   Makeup 
   Hairstyles
social:
  #twitter: joaomlneto
  #facebook: joaomlneto
  instagram: anuavneettoor
  instagram: k_jessiie
  #github: grace-esthetics-yeg
  #linkedin:

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
